name: 'CI'
on:
  # Triggers the workflow on push or pull request events but only for the beta branch
  push:
    branches: [ beta ]
    paths:
      - az.avd/**
  pull_request:
    branches: [ beta ]
    paths:
      - az.avd/**


jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          fromTag: "v3.0.1-beta.2"
          toTag: "v3.0.1-beta.3"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
